### ISSUE TITLE
Akhil - Frontend 2

### ISSUE THREAD

**Issue by Akhil353** [APCSP-RAGS/pp-frontend#3]
- [x] Start adding onto Alien Background
- [x] Work on displaying data from JSON file as a table
    - [x] Create table for songs and jokes

**Comment by Akhil353** [comment]
Summary

[Commit 1](https://github.com/APCSP-RAGS/pp-frontend/commit/da349b5185be9c92df7b06c344f38b507fd2f91f)
Got the table working for jokes

Problems I faced
    - The Jupyter notebook file didn't work as the website can't run the code blocks
        - Fix: Move the page into a .md file for the code to run

[Commit 2](https://github.com/APCSP-RAGS/pp-frontend/commit/eac493760475a8308e3497111087b2f1c1eee1f2)
Created the table for character songs

Problems I faced
    - The table didn't run as the fetch command was used wrongly
        - Fix: Put the url for the data in the fetch command
    - The ID column said undefined as there was no data for the id
        - Fix: Remove the ID column

**Comment by aashrayr** [comment]
Summary

[Commit 1](https://github.com/APCSP-RAGS/pp-frontend/commit/da349b5185be9c92df7b06c344f38b507fd2f91f)
Added base code for the table

Problems I faced
- The Jupyter notebook file didn't work as the website can't run the code blocks
- Fix: Move the page into a .md file for the code to run

[Commit 2](https://github.com/APCSP-RAGS/pp-frontend/commit/eac493760475a8308e3497111087b2f1c1eee1f2)
Helped with input output for the music generators
Problems I faced
- The table didn't run as the fetch command was used wrongly
- Fix: Put the url for the data in the fetch command
